version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
      - ./.env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    depends_on:
      - backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
      - ./.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
